/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/6834cf7f-46fb-4ab8-a40d-7c4ab24737ed 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float boardHUMID;
  float boardTEMP;
  bool button;
  bool redLED;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

// DHT sensor library - Version: Latest 
#include <DHT.h>
#include <DHT_U.h>

#define DHTPIN 12
#define DHTTYPE DHT11

DHT dht(DHTPIN,DHTTYPE);

int buttonPin=15;
int myLED=13;

int switchState = 0; // actual read value from pin4
int oldSwitchState = 0; // last read value from pin4
int lightsOn = 0; // is the switch on = 1 or off = 0
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(150); 

  // Defined in thingProperties.h
  initProperties();
  
  pinMode(myLED,OUTPUT);
  pinMode(buttonPin,INPUT);
  pinMode(DHTPIN,INPUT);
  dht.begin();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  switchState = digitalRead(buttonPin); // read the pushButton State
 if (switchState != oldSwitchState) // catch change
 {
 oldSwitchState = switchState;
 if (switchState == HIGH)
 {
 // toggle
 lightsOn = !lightsOn;
 }
 }
 if(lightsOn)
 {
 digitalWrite(myLED, HIGH); // set the LED on
 boardTEMP=dht.readTemperature();
 boardHUMID=dht.readHumidity();
 } else {
 digitalWrite(myLED, LOW); // set the LED off
 }
 
  delay(3000);
} 


/*
  Since RedLED is READ_WRITE variable, onRedLEDChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRedLEDChange()  {
  // Add your code here to act upon RedLED change
  

}

/*
  Since Button is READ_WRITE variable, onButtonChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onButtonChange()  {
 if(button==true)
 {
   digitalWrite(redLED,HIGH);
   boardTEMP=dht.readTemperature();
 boardHUMID=dht.readHumidity();
 }
 else
 {
   digitalWrite(redLED,LOW);
 }
 delay(3000);
  
}
